# Site wide configuration

title:            JSPcore
locale:           en_US
url:              https://www.jspcore.com
#url:              http://localhost:4000

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Javier Salinas
  avatar: bio-photo.jpg
  bio: "Software Engineer located in Barcelona, interested in Distributed Systems and simple designs using TDD."
  email: jsalinaspolo@gmail.com
  disqus-shortname: jspcore
  twitter: jsalinaspolo
  google:
      plus: JavierSalinasPolo
      analytics: UA-37453172-1
      verify:
      ad-client:
      ad-slot:
  github: #username
  stackoverflow: 1300594/javier-salinas
  linkedin: jsalinaspolo

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

plugins:
  - jekyll-gist
theme: jekyll-theme-minimal
